baseurl = "https://apinf.org/"
languageCode = "en-us"
title = "APInf Project Site"
theme = "apinf-theme"

[params]
name = "APINF"
description = "Discover and manage APIs"

# The path must be relative to the static folder
favicon = "../img/favicon.ico"


# Navigation
[params.navigation]
brand = "APINF"

[params.navigation.links]
about     = "About"
opensource= "Open source"
features  = "Features"
services = "Services"
documentation 	= "Documentation"
team 			= "Team"
contact 	= "Contact"
blog   		= "Blog"


# Hero section
[params.hero]
slogan     = "Discover and manage APIs"
subtitle   = "Develop. We do the rest."
register = "Get started"
explore = "Explore APIs"

[[params.hero.meta.list]]
link = "http://apinf.org/docs/"
text = "Documentation"

[[params.hero.meta.list]]
link = "https://github.com/apinf/platform/releases"
text = "What's new"

[params.hero.links]
github = "Star on Github"
twitter = "Follow @apinf_io on Twitter"


# About section
[params.about]
headline    = "Simple API Management"
description = "APInf platform offers a comprehensive, yet easy to use API management tool. APInf provides simplified workflow for API owners for common API management tasks. At the same time, it serves as a self-service tool for API consumers for discovering APIs and taking them to use."
buttonText = "Discover more"
screenshot = "../img/dashboard.png"


# Features
[params.features]
headline = "Here's how it works"
owner = "Owner"
user = "User"

# Users section
[params.features.users]
headline = "One stop shop to discover APIs and start using them!"

[[params.features.users.list]]
image = "img/discover.jpg"
title = "Discover APIs"
description = "Find and bookmark useful APIs"

[[params.features.users.list]]
image = "img/documentation.jpg"
title = "Read API documentation"
description = "Swagger viewer available"

[[params.features.users.list]]
image = "img/apikey.jpg"
title = "Get the API key"
description = "Sign up and get your API key"

# Owners section
[params.features.owners]
headline = "Focus on building your APIs, while having unified API management features."

[[params.features.owners.list]]
image = "img/add-api.jpg"
title = "Publish your APIs"
description = "Make your APIs easily available for developers"

[[params.features.owners.list]]
image = "img/proxy.jpg"
title = "Connect the API to a proxy"
description = "Select the right proxy for your API"

[[params.features.owners.list]]
image = "img/dashboard.jpg"
title = "Track and manage"
description = "Easily manage and configure your API endpoints and access control"


# Services
[params.services]
headline = "Services"
description = "From consultation to deployment, the APInf team is here to help you get the most out of APIs and APInf."
contactText = "If you have any questions about our services, get in touch. We would love to hear from you."
buttonText = "Contact us"

[[params.services.list]]
title = "Self-hosted deployments"
description = "Do you want to run your own APInf instance? Save time by allowing our specialist to set up the deployment for you and manage it."

[[params.services.list]]
title = "Whitelabeling and customization"
description = "Get your own brand colors, logos, home page for your deployment."

[[params.services.list]]
title = "Custom development"
description = "Do you have any specific needs not covered in our current APInf version? Let us know about your custom needs."

[[params.services.list]]
title = "Onboarding to apinf.io SaaS"
description = "Our specialists can help you to add your APIs to our SaaS version and train you in common API management tasks."

[[params.services.list]]
title = "API consultancy and training"
description = "Learn about common best practices for web APIs from our specialists."

[[params.services.list]]
title = "API design and Swagger"
description = "If you are a newcomer to APIs, we can help you with API design and documentation."


# Opensource section
[params.opensource]
headline = "We don’t just talk about Open Source, we live it too."
description = "APinf is powered by API Umbrella and builds a dashboard on top of the API Umbrella features. The solution is fully open source licensed with MIT. We have gone one step further with our open process. We like to collaborate, to listen to our users and want to encourage people to become contributors."

[[params.opensource.list]]
buttonText = "Github"
link = "https://github.com/apinf"

[[params.opensource.list]]
buttonText = "Community"
link = "https://community.apinf.io/"


# Team section
[params.team]
headline = "Core team"

[[params.team.list]]
name = "Chandra Challagonda"
title = "CEO"
photo = "/img/team/chandra.jpg"
twitter = "https://twitter.com/challagonda"
linkedin = "https://linkedin.com/in/challagonda"

[[params.team.list]]
name = "Taija Björklund"
title = "Product Owner"
photo = "/img/team/taija.jpg"
twitter = "https://twitter.com/TaijaBjorklund"
medium = "https://medium.com/@TaijaBjorklund"

[[params.team.list]]
name = "Philippe Luickx"
title = "Business Developer"
photo = "/img/team/phillipe.jpg"
twitter = "https://twitter.com/PhilippeLuickx"
linkedin = "https://www.linkedin.com/in/philippeluickx"
medium = "https://medium.com/@PhilippeLuickx"

[[params.team.list]]
name = "Brylie Oxley"
title = "Architect"
photo = "/img/team/brylie.jpg"
github = "https://github.com/brylie"

[[params.team.list]]
name = "Laura Ekman"
title = "Marketing Manager"
photo = "/img/team/laura.jpg"
linkedin = "https://linkedin.com/in/laura-ekman"
medium = "https://medium.com/@lauraekman"

[[params.team.list]]
name = "Vesa Härkönen"
title = "Internal Customer"
photo = "/img/team/vesa.jpg"
linkedin = "https://www.linkedin.com/in/vesa-h%C3%A4rk%C3%B6nen-1514891"

[[params.team.list]]
name = "Ville Jyrkkä"
title = "SW Developer"
photo = "/img/team/ville.jpg"
twitter = "https://twitter.com/jykae"
github = "https://github.com/jykae"
linkedin = "https://fi.linkedin.com/in/vjyrkka"

[[params.team.list]]
name = "Nazia Hasan"
title = "UX Designer"
photo = "/img/team/nazia.jpg"
twitter = "https://twitter.com/NazarahTheCat"
linkedin = "https://linkedin.com/in/naziahasan"

[[params.team.list]]
name = "Illya Nizyev"
title = "SW Developer"
photo = "/img/team/illya.jpg"
github = "https://github.com/nnn"

[[params.team.list]]
name = "Damir Mustafin"
title = "SW Developer"
photo = "/img/team/damir.jpg"
github = "https://github.com/frenchbread"

[[params.team.list]]
name = "Daria Voytova"
title = "SW Developer"
photo = "/img/team/dasha.jpg"
github = "https://github.com/marla-singer"

[[params.team.list]]
name = "Shaliko Usubov"
title = "DevOPS"
photo = "/img/team/shaliko.jpg"
twitter = "https://twitter.com/usubov"
github = "https://github.com/shaliko"


# Contact section
[params.contact.start]
headline = "Get started"
description = "Sounds like what you've been looking for? Sign in to apinf.io and get going!"

[params.contact]
headline = "Get in touch"
description = "If you are using APInf, interested in contributing, or looking for commercial support, we'd love to hear about it. Please contact us."


# Footer section
[params.footer]
copyright = "2016 APInf - API Management Platform, a creation of Sampo Software Oy."

[[params.footer.links.list]]
link = "https://twitter.com/apinf_io"
icon = "twitter"

[[params.footer.links.list]]
link = "https://www.facebook.com/APInf.io"
icon = "facebook"

[[params.footer.links.list]]
link = "https://github.com/apinf"
icon = "github-circle"

[[params.footer.links.list]]
link = "https://medium.com/apinf"
icon = "medium"
