baseurl = "https://apinf.org/"
languageCode = "en-us"
title = "APInf Project Site"
theme = "apinf-theme"

[params]

	name = "APINF"
	description = "API Management Platform"

	# The path must be relative to the static folder
	favicon = "/favicon.ico"


	# Navigation
	[params.navigation]
		brand = "APINF"

		[params.navigation.links]
			about     = "About"
			opensource= "Opensource"
			features  = "Features"
			services = "Services"
			documentation 	= "Documentation"
			team 			= "Team"
			contact 	= "Contact"
			blog   		= "Blog"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "API Management Platform"
		subtitle   = "Develop. We do the rest."
		buttonText = "Get started"


	# About section
	[params.about]
		headline    = "Simple API Management"
		description = "APInf platform offers a comprehensive, yet easy to use API management tool. APInf provides simplified workflow for API owners for common Api management tasks. At the same time, it serves as a self-service tool for API consumers for discovering APIs and taking them to use."
		buttonText = "Discover more"

# Features
	# Users section
	[params.features.users]
		headline = "Are you an API user?"

		[[params.features.users.list]]
	    icon = "mdi-magnify"
	    title = "Discover APIs"
	    description = "Find and bookmark useful APIs"

		[[params.features.users.list]]
			icon = "mdi-key"
			title = "Get API key"
			description = "Sign up and get your API key"

		[[params.features.users.list]]
	    icon = "mdi-file-document-box"
	    title = "Check API documentation"
	    description = "Swagger viewer available"

		[[params.features.users.list]]
	    icon = "mdi-pot-mix"
	    title = "Mix APIs"
	    description = "Mix APIs from several sources"

	# Owners section
	[params.features.owners]
		headline = "Are you an API owner?"

		[[params.features.owners.list]]
	    icon = "mdi-arrow-up-bold"
	    title = "Publish your APIs"
	    description = "Make your APIs easily available for developers"

		[[params.features.owners.list]]
			icon = "mdi-settings"
			title = "Manage your APIs"
			description = "Easily manage and configure your API endpoints and access control"

		[[params.features.owners.list]]
	    icon = "mdi-chart-line"
	    title = "Track your APIs"
	    description = "View detailed analytics data for your APIs"

		[[params.features.owners.list]]
	    icon = "mdi-domain"
	    title = "Select your proxy"
	    description = "Select the right proxy for your API"

		# Features
			# Users section
			[params.services]
				headline = "Services"
				description = "From consultation to deployment, the APInf team is here to help you get the most out of APIs and APInf."

				[[params.services.list]]
			    title = "Self-hosted deployments"
			    description = "Find and bookmark useful APIs"

				[[params.services.list]]
					title = "Whitelabeling and customization"
					description = "Sign up and get your API key"

				[[params.services.list]]
			    title = "Custom development"
			    description = "Swagger viewer available"

				[[params.services.list]]
			    title = "Onboarding to apinf.io SaaS"
			    description = "Mix APIs from several sources"

				[[params.services.list]]
					title = "API consultancy and training"
					description = "Mix APIs from several sources"

				[[params.services.list]]
					title = "API design and Swagger"
					description = "Mix APIs from several sources"

    # Opensource section
	[params.opensource]
		headline = "We don’t just talk about Open Source, we live it too."
		description = "APinf is powered by API Umbrella and builds a dashboard on top of the API Umbrella features. The solution is fully open source licensed with MIT. It is written in Meteor.js and D3. We like to collaborate, to listen to our users and want to encourage people to become contributors."

		[[params.opensource.list]]
	    buttonText = "Text"

		[[params.opensource.list]]
			buttonText = "Text"

		[[params.opensource.list]]
			buttonText = "Text"

		[[params.opensource.list]]
	    buttonText = "Text"

	  # Team section
		[params.team]
			headline = "Core team"

			[[params.team.list]]
				name = "Chandra Challagonda"
				title = "CEO"
				photo = "/img/team/chandra.jpg"
				twitter = "https://twitter.com"
				github = ""
				linkedin = ""
				medium = ""

			[[params.team.list]]
				name = "Taija Björklund"
				title = "Product Owner"
				photo = "/img/team/taija.jpg"
				twitter = "https://twitter.com/TaijaBjorklund"
				medium = "https://medium.com/@TaijaBjorklund"

			[[params.team.list]]
				name = "Philippe Luickx"
				title = "Business Developer"
				photo = "/img/team/phillipe.jpg"
				twitter = "https://twitter.com"
				github = ""
				linkedin = ""
				medium = ""

			[[params.team.list]]
				name = "Brylie Oxley"
				title = "Architect"
				photo = "/img/team/brylie.jpg"
				twitter = "https://twitter.com"
				github = ""
				linkedin = ""
				medium = ""

			[[params.team.list]]
				name = "Laura Ekman"
				title = "Marketing Coordinator"
				photo = "/img/team/laura.jpg"
				linkedin = "https://linkedin.com/in/laura-ekman"
				medium = "https://medium.com/@lauraekman"

			[[params.team.list]]
				name = "Vesa Härkönen"
				title = "Internal Customer"
				photo = "/img/team/vesa.jpg"
				twitter = "https://twitter.com"
				github = ""
				linkedin = ""
				medium = ""

			[[params.team.list]]
				name = "Ville Jyrkkä"
				title = "SW Developer"
				photo = "/img/team/ville.jpg"
				twitter = "https://twitter.com/jykae"
				github = "https://github.com/jykae"
				linkedin = "https://fi.linkedin.com/in/vjyrkka"

			[[params.team.list]]
				name = "Nazia Hasan"
				title = "UX Designer"
				photo = "/img/team/nazia.jpg"
				twitter = "https://twitter.com/NazarahTheCat"
				linkedin = "https://linkedin.com/in/naziahasan"

			[[params.team.list]]
				name = "Illya Nizyev"
				title = "SW Developer"
				photo = "/img/team/illya.jpg"
				github = "https://github.com/nnn"

			[[params.team.list]]
				name = "Damir Mustafin"
				title = "SW Developer"
				photo = "/img/team/damir.jpg"
				twitter = "https://twitter.com"
				github = ""
				linkedin = ""
				medium = ""

			[[params.team.list]]
				name = "Daria Voytova"
				title = "SW Developer"
				photo = "/img/team/dasha.jpg"
				github = "https://github.com/marla-singer"

			[[params.team.list]]
				name = "Shaliko Usubov"
				title = "DevOPS"
				photo = "/img/team/shaliko.jpg"
				twitter = "https://twitter.com/usubov"
				github = "https://github.com/shaliko"

	# Contact section
	[params.contact]
		headline = "How may we help you?"
		description = "We want your input, questions, bug reports, complaints, praise, feature requests - every little bit helps."
		email = "info@apinf.io"
