baseurl = "https://apinf.org/"
languageCode = "en-us"
title = "APInf Project Site"
theme = "apinf-theme"

[params]

	name = "APINF"
	description = "API Management Platform"

	# The path must be relative to the static folder
	favicon = "/favicon.ico"


	# Navigation
	[params.navigation]
		brand = "APINF"

		[params.navigation.links]
			about     = "About"
			opensource= "Opensource"
			features  = "Features"
			documentation 	= "Documentation"
			team 			= "Team"
			contact 	= "Contact"
			blog   		= "Blog"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "API Management Platform"
		subtitle   = "Develop. We do the rest."
		buttonText = "Get started"


	# About section
	[params.about]
		headline    = "Simple API Management"
		description = "APInf platform offers a comprehensive, yet easy to use API management tool. APInf provides simplified workflow for API owners for common Api management tasks. At the same time, it serves as a self-service tool for API consumers for discovering APIs and taking them to use."
		buttonText = "Discover more"

# Features
	# Users section
	[params.features.users]
		headline = "Are you an API user?"

		[[params.features.users.list]]
	    icon = "mdi-magnify"
	    title = "Discover APIs"
	    description = "Find and bookmark useful APIs"

		[[params.features.users.list]]
			icon = "mdi-key"
			title = "Get API key"
			description = "Sign up and get your API key"

		[[params.features.users.list]]
	    icon = "mdi-file-document-box"
	    title = "Check API documentation"
	    description = "Swagger viewer available"

		[[params.features.users.list]]
	    icon = "mdi-pot-mix"
	    title = "Mix APIs"
	    description = "Mix APIs from several sources"

	# Owners section
	[params.features.owners]
		headline = "Are you an API owner?"

		[[params.features.owners.list]]
	    icon = "mdi-arrow-up-bold"
	    title = "Publish your APIs"
	    description = "Make your APIs easily available for developers"

		[[params.features.owners.list]]
			icon = "mdi-settings"
			title = "Manage your APIs"
			description = "Easily manage and configure your API endpoints and access control"

		[[params.features.owners.list]]
	    icon = "mdi-chart-line"
	    title = "Track your APIs"
	    description = "View detailed analytics data for your APIs"

		[[params.features.owners.list]]
	    icon = "mdi-domain"
	    title = "Select your proxy"
	    description = "Select the right proxy for your API"

    # Opensource section
	[params.opensource]
		headline = "We don’t just talk about Open Source, we live it too."
		description = "APinf is powered by API Umbrella and builds a dashboard on top of the API Umbrella features. The solution is fully open source licensed with MIT. It is written in Meteor.js and D3. We like to collaborate, to listen to our users and want to encourage people to become contributors."

		[[params.opensource.list]]
	    buttonText = "Text"

		[[params.opensource.list]]
			buttonText = "Text"

		[[params.opensource.list]]
			buttonText = "Text"

		[[params.opensource.list]]
	    buttonText = "Text"

	    # Team section
		[params.team]
			headline = "Our team"
			description	= "People behind APINF"

	# Contact section
	[params.contact]
		headline = "How may we help you?"
		description = "We want your input, questions, bug reports, complaints, praise, feature requests - every little bit helps."
		email = "info@apinf.io"
