baseurl = "https://apinf.org/"
languageCode = "en-us"
title = "APInf Project Site"
theme = "apinf-theme"

[params]

	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "/favicon.ico"


	# Navigation
	[params.navigation]
		brand = "APINF"

		[params.navigation.links]
			about     = "About"
			services  = "Features"
			team 			= "Team"
			contact 	= "Contact"
			blog   		= "Blog"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "API Management Platform"
		subtitle   = "Building a bridge between API owners and users"
		buttonText = "Get started"


	# About section
	[params.about]
		headline    = "Sleek dashboard"
		description = "APInf platform offers a comprehensive, yet easy to use API management tool. APInf provides simplified workflow for API owners for common Api management tasks. At the same time, it serves as a self-service tool for API consumers for discovering APIs and taking them to use."


	# Service section
	[params.services]
		headline = "Are you an API user?"

        [[params.services.list]]
            icon = "mdi-diamond"
            title = "Discover APIs"
            description = "Find and bookmark useful APIs"

        [[params.services.list]]
			icon = "mdi-send"
			title = "Get API key"
			description = "Sign up and get your API key"

		[[params.services.list]]
            icon = "mdi-newspaper"
            title = "Check API documentation"
            description = "Swagger viewer available"

        [[params.services.list]]
            icon = "mdi-heart"
            title = "Mix APIs"
            description = "Mix APIs from several sources"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Start managing APIs now"

		[params.aside.button]
			text = "Get started"
			link = "//apinf.io"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
