name = "Apinf"
license = "Apache License 2.0"
min_version = 0.1

[author]
  name = "apinf"
  homepage = "//github.com/apinf"

# If porting an existing theme
[original]
  name = "David Miller"
  homepage = "//www.ironsummitmedia.com/"
  repo = "//github.com/IronSummitMedia/startbootstrap-creative"
